# Image Thresholding

In [1]:
import cv2
import numpy as np

In [2]:
im1=cv2.imread("img1.jfif")
im2=cv2.imread("img2.jfif")

In [3]:
print(im1.shape)
print(im2.shape)

(180, 216, 3)
(180, 267, 3)


In [4]:
im1

array([[[237, 177, 111],
        [237, 177, 111],
        [237, 177, 111],
        ...,
        [237, 177, 111],
        [237, 177, 111],
        [237, 177, 111]],

       [[235, 175, 109],
        [235, 175, 109],
        [235, 175, 109],
        ...,
        [235, 175, 109],
        [235, 175, 109],
        [235, 175, 109]],

       [[233, 174, 105],
        [233, 174, 105],
        [233, 174, 105],
        ...,
        [233, 174, 105],
        [233, 174, 105],
        [233, 174, 105]],

       ...,

       [[ 27,  77,  29],
        [ 28,  75,  29],
        [ 34,  77,  34],
        ...,
        [ 90, 146,  57],
        [ 96, 157,  66],
        [ 83, 147,  52]],

       [[  3,  53,   5],
        [  0,  45,   0],
        [  2,  45,   2],
        ...,
        [ 35,  93,   5],
        [ 52, 114,  24],
        [ 43, 108,  16]],

       [[  0,  47,   0],
        [  0,  36,   0],
        [  0,  33,   0],
        ...,
        [ 32,  92,   4],
        [ 36,  98,   8],
        [ 46, 111,  19]]

In [5]:
im2

array([[[253, 247, 242],
        [250, 244, 239],
        [251, 245, 240],
        ...,
        [254, 253, 249],
        [254, 253, 249],
        [254, 253, 249]],

       [[249, 243, 238],
        [246, 240, 235],
        [247, 241, 236],
        ...,
        [254, 253, 249],
        [254, 253, 249],
        [254, 253, 249]],

       [[248, 242, 237],
        [244, 238, 233],
        [244, 238, 233],
        ...,
        [254, 253, 249],
        [254, 253, 249],
        [254, 253, 249]],

       ...,

       [[244, 235, 222],
        [246, 238, 225],
        [234, 225, 216],
        ...,
        [224, 218, 211],
        [224, 218, 211],
        [224, 218, 211]],

       [[245, 236, 223],
        [248, 240, 227],
        [236, 227, 218],
        ...,
        [227, 221, 214],
        [227, 221, 214],
        [227, 221, 214]],

       [[247, 238, 225],
        [250, 242, 229],
        [238, 229, 220],
        ...,
        [230, 224, 217],
        [230, 224, 217],
        [230, 224, 217]]

In [6]:
im1_shape=im1.shape
im2_shape=im2.shape

In [7]:
im1_resized=cv2.resize(im1,(230,290))
im2_resized=cv2.resize(im2,(230,290))

In [8]:
cv2.imshow("Sample1",im1_resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
cv2.imshow("Sample2",im2_resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
ret,thres1=cv2.threshold(im1,83,100,cv2.THRESH_BINARY)
ret,thres2=cv2.threshold(im1,83,100,cv2.THRESH_BINARY_INV)
ret,thres3=cv2.threshold(im1,83,100,cv2.THRESH_TRUNC)
ret,thres4=cv2.threshold(im1,83,100,cv2.THRESH_TOZERO)
ret,thres5=cv2.threshold(im1,83,100,cv2.THRESH_TOZERO_INV)

In [12]:
thres1

array([[[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [100, 100,   0],
        [100, 100,   0],
        [  0, 100,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 100,   0],
        [  0, 100,   0],
        [  0, 100,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 100,   0],
        [  0, 100,   0],
        [  0, 100,   0]]

In [13]:
thres2

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [  0,   0, 100],
        [  0,   0, 100],
        [100,   0, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100,   0, 100],
        [100,   0, 100],
        [100,   0, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100,   0, 100],
        [100,   0, 100],
        [100,   0, 100]]

In [14]:
thres3

array([[[83, 83, 83],
        [83, 83, 83],
        [83, 83, 83],
        ...,
        [83, 83, 83],
        [83, 83, 83],
        [83, 83, 83]],

       [[83, 83, 83],
        [83, 83, 83],
        [83, 83, 83],
        ...,
        [83, 83, 83],
        [83, 83, 83],
        [83, 83, 83]],

       [[83, 83, 83],
        [83, 83, 83],
        [83, 83, 83],
        ...,
        [83, 83, 83],
        [83, 83, 83],
        [83, 83, 83]],

       ...,

       [[27, 77, 29],
        [28, 75, 29],
        [34, 77, 34],
        ...,
        [83, 83, 57],
        [83, 83, 66],
        [83, 83, 52]],

       [[ 3, 53,  5],
        [ 0, 45,  0],
        [ 2, 45,  2],
        ...,
        [35, 83,  5],
        [52, 83, 24],
        [43, 83, 16]],

       [[ 0, 47,  0],
        [ 0, 36,  0],
        [ 0, 33,  0],
        ...,
        [32, 83,  4],
        [36, 83,  8],
        [46, 83, 19]]], dtype=uint8)

In [15]:
thres4

array([[[237, 177, 111],
        [237, 177, 111],
        [237, 177, 111],
        ...,
        [237, 177, 111],
        [237, 177, 111],
        [237, 177, 111]],

       [[235, 175, 109],
        [235, 175, 109],
        [235, 175, 109],
        ...,
        [235, 175, 109],
        [235, 175, 109],
        [235, 175, 109]],

       [[233, 174, 105],
        [233, 174, 105],
        [233, 174, 105],
        ...,
        [233, 174, 105],
        [233, 174, 105],
        [233, 174, 105]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 90, 146,   0],
        [ 96, 157,   0],
        [  0, 147,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,  93,   0],
        [  0, 114,   0],
        [  0, 108,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,  92,   0],
        [  0,  98,   0],
        [  0, 111,   0]]

In [16]:
thres5

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       ...,

       [[27, 77, 29],
        [28, 75, 29],
        [34, 77, 34],
        ...,
        [ 0,  0, 57],
        [ 0,  0, 66],
        [83,  0, 52]],

       [[ 3, 53,  5],
        [ 0, 45,  0],
        [ 2, 45,  2],
        ...,
        [35,  0,  5],
        [52,  0, 24],
        [43,  0, 16]],

       [[ 0, 47,  0],
        [ 0, 36,  0],
        [ 0, 33,  0],
        ...,
        [32,  0,  4],
        [36,  0,  8],
        [46,  0, 19]]], dtype=uint8)

In [17]:
print(ret)

83.0


In [20]:
cv2.imshow("Thres_img1",thres1)
cv2.imshow("Thres_img2",thres2)
cv2.imshow("Thres_img3",thres3)
cv2.imshow("Thres_img4",thres4)
cv2.imshow("Thres_img5",thres5)
cv2.waitKey(0)
cv2.destroyAllWindows()